Adds an Edit Profile link to the admin bar
strangerstudios/pmpro-member-directory pull request #102
Opened 2022-02-04 10:39 UTC by JarrydLong

- Navigate to your directory page
- Click on a user's profile
- You can now edit that specific user's profile

![image](https://user-images.githubusercontent.com/8989542/152515046-c03aee54-e374-4b9a-ab9f-d0a75547503a.png)

2022-02-15 04:14 UTC, sc0ttkclark commented on pmpro-member-directory.php
> +		        'title' => __( 'Edit Profile', 'pmpro-member-directory' ),
```suggestion
		        'title' => esc_html__( 'Edit Profile', 'pmpro-member-directory' ),
```

2022-02-15 04:20 UTC, sc0ttkclark commented on pmpro-member-directory.php
> +		            'title' => __( 'Edit Profile', 'pmpro-member-directory' ),
Just a note here -- the meta attributes are escaped via esc_attr() ultimately.

2022-02-15 04:20 UTC, sc0ttkclark requested changes
Minor escape tweak here

2022-03-18 12:29 UTC, ideadude commented on pmpro-member-directory.php
> +		    $admin_bar->add_menu( array(
```suggestion
		    // Note: The title is escaped here. The URL and meta attributes are escaped by the WP Admin Bar class.
		    $admin_bar->add_menu( array(
```

2022-03-18 12:29 UTC, merged