Numbered Pagination Added
strangerstudios/pmpro-member-directory pull request #104
Opened 2022-02-09 11:38 UTC by JarrydLong

Relates to #95

When on Page 1 
![pagination-pt-1](https://user-images.githubusercontent.com/8989542/153192495-2afa0a71-aea1-4051-80d1-14feea5c46f0.PNG)

After moving further along the page numbers

![pagination-pt-2](https://user-images.githubusercontent.com/8989542/153192500-ba629a82-596b-4ef3-a944-df4f3dc77849.PNG)

2022-02-15 03:27 UTC, sc0ttkclark commented on templates/directory.php
> +		}
```suggestion
		if ( empty( $pn ) || $pn != 1 ) {
			echo '<a href="' . esc_url( add_query_arg( $query_args, get_permalink( $post->ID ) ) ) . '" title="' . esc_attr__( 'Previous', 'pmpromd' ) . '">...</a>';
		}

```

2022-02-15 03:28 UTC, sc0ttkclark commented on templates/directory.php
> +				echo '<a href="'. esc_url(add_query_arg( $query_args, get_permalink($post->ID))).'" '.$active_class.' title="'.sprintf( __('Page %s', 'pmpromd' ), $i ).'">'.$i.'</a>';
```suggestion
				echo '<a href="' . esc_url( add_query_arg( $query_args, get_permalink( $post->ID ) ) ) . '" ' . $active_class . ' title="' . esc_attr( sprintf( __('Page %s', 'pmpromd' ), $i ) ) . '">' . $i . '</a>';
```

2022-02-15 03:29 UTC, sc0ttkclark requested changes
Minor tweak but there's some escaping to do

2022-03-18 08:26 UTC, merged

2022-03-18 08:26 UTC, andrewlimaza commented
Merging in as items have been escaped.