Filter added to directory attributes
strangerstudios/pmpro-member-directory pull request #82
Opened 2020-11-24 12:51 UTC by JarrydLong

Relates to https://github.com/strangerstudios/pmpro-membership-maps/issues/24

Filter added to the array that feeds into the before member directory action. Needed in Membership Maps

2022-02-15 04:29 UTC, sc0ttkclark commented on templates/directory.php
> +			$shortcode_atts = apply_filters( 'pmpro_member_directory_before_atts', array(
Let's get phpdoc for this hook added

2022-02-15 04:29 UTC, sc0ttkclark requested changes
Hook needs phpdoc info

2022-03-18 12:07 UTC, ideadude commented on templates/directory.php
> +			 * @param array Contain all of the shortcode attributes used in the directory shortcode
```suggestion
			 * @param array Contains all of the shortcode attributes used in the directory shortcode
```

2022-03-18 12:07 UTC, ideadude commented on templates/directory.php
> +			 * Include the default level billing price at checkout as a radio checkbox.
```suggestion
			 * Filter to override the attributes passed into the shortcode.
```

2022-03-18 12:07 UTC, merged